#!/usr/bin/env bash

set -o pipefail

function test_workflow    { cat .github/workflows/test.yaml ; }
function install_commands { yq '.jobs.test.steps[] | select(.name == "Install tools") | .run' ; }

test_workflow | install_commands | while read COMMAND
do
	echo ${COMMAND}
	TEMPFILE=$(mktemp)
	eval ${COMMAND} >${TEMPFILE} \
	 && { rm ${TEMPFILE}; } \
	 || { cat ${TEMPFILE}; rm ${TEMPFILE}; exit 1; }
done
