on: push
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install staticcheck
      run: pwd && cd .. && go get -v -u honnef.co/go/tools/cmd/staticcheck && cd -
      shell: bash
    - name: Install golint
      run: pwd && cd .. && go get -v -u golang.org/x/lint/golint && cd -
      shell: bash
    - name: Update PATH
      # https://github.com/actions/setup-go/issues/12#issuecomment-524631719
      run: echo "##[add-path]$(go env GOPATH)/bin" 
      shell: bash
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Fmt
      if: matrix.platform != 'windows-latest' # :(
      run: "F=$(gofmt -l .) ; if [[ $F ]] ; then echo $F ; exit 1 ; fi"
      shell: bash
    - name: Vet
      run: go vet ./...
    - name: Staticcheck
      run: staticcheck ./...
    - name: Lint
      run: golint ./...
    - name: Parallel tests
      run: hack/lint-parallel-tests.bash
    - name: Test
      run: go test -race ./...
